services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    volumes:
      - ./app/backend:/app
    environment:
      DATABASE_URL: postgres://user:password@postgres/mydatabase
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - mynetwork

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    volumes:
      - ./app/frontend:/app
    ports:
      - 8501:8501
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

networks:
  mynetwork:


volumes:
  postgres_data:
